# -*- coding: utf-8 -*-
from __future__ import annotations

from enum import Enum
from dataclasses import dataclass
from .category_kind import CategoryKindEnum


@dataclass(frozen=False)
class FunctionKind:
    """Examines the class FunctionKindEnum to find fields. 
    """
    function: str
    code: str
    geometry: list
    category: str


class FunctionKindEnum(Enum):
    """Enum Class consist of kind of monuments funcions as members.
    """
    ZABYTEK_NIERUCHOMY = FunctionKind(
        function="zabytek nieruchomy",
        code='1',
        geometry=[''],
        category='')
    KRAJOBRAZ_KULTUROWY = FunctionKind(
        function="krajobraz kulturowy",
        code='11',
        geometry=['POLYGON'],
        category='')
    HISTORYCZNY_UKLAD_PRZESTRZENNY = FunctionKind(
        function="historyczny układ przestrzenny",
        code='12',
        geometry=['POLYGON', 'LINE'],
        category='')
    HISTORYCZNY_ZESPOL_BUDOWLANY = FunctionKind(
        function="historyczny zespół budowlany",
        code='13',
        geometry=[''],
        category='')
    DZIELO_ARCHITEKTURY_I_BUDOWNICTWA = FunctionKind(
        function="dzieło architektury i budownictwa",
        code='14',
        geometry=[''],
        category='')
    BUDYNEK_REZYDENCJONALNY = FunctionKind(
        function="budynek rezydencjonalny",
        code='141',
        geometry=['POLYGON', 'POINT'],
        category='')
    BUDYNEK_MIESZKALNY = FunctionKind(
        function="budynek mieszkalny",
        code='142',
        geometry=['POLYGON', 'POINT'],
        category='')
    BUDYNEK_GOSPODARCZY = FunctionKind(
        function="budynek gospodarczy",
        code='143',
        geometry=['POLYGON', 'POINT'],
        category='')
    BUDYNEK_PRZEMYSLOWY = FunctionKind(
        function="budynek przemysłowy",
        code='144',
        geometry=['POLYGON', 'POINT'],
        category='')
    BUDYNEK_UZYTECZNOSCI_PUBLICZNEJ = FunctionKind(
        function="budynek użyteczności publicznej",
        code='145',
        geometry=['POLYGON', 'POINT'],
        category='')
    BUDYNEK_SAKRALNY = FunctionKind(
        function="budynek sakralny",
        code='146',
        geometry=['POLYGON', 'POINT'],
        category='')
    MALA_ARCHITEKTURA = FunctionKind(
        function="mała architektura",
        code='147',
        geometry=['POLYGON', 'POINT'],
        category='')
    INNE_DZIELO_ARCHITEKTURY_I_BUDOWNICTWA = FunctionKind(
        function="inne dzieło architektury i budownictwa",
        code='148',
        geometry=['POLYGON', 'LINE', 'POINT'],
        category='')
    DZIELO_TECHNIKI_I_PRZEMYSLOWE = FunctionKind(
        function="dzieło techniki i przemysłowe",
        code='15',
        geometry=['POLYGON', 'LINE', 'POINT'],
        category='')
    DZIELO_BUDOWNICTWA_OBRONNEGO = FunctionKind(
        function="dzieło budownictwa obronnego",
        code='16',
        geometry=[''],
        category='')
    TWIERDZA = FunctionKind(
        function="twierdza",
        code='161',
        geometry=['POLYGON', 'POINT'],
        category='')
    ZAMEK = FunctionKind(
        function="zamek",
        code='162',
        geometry=['POLYGON', 'POINT'],
        category='')
    DWOR_OBRONNY = FunctionKind(
        function="dwór obronny",
        code='163',
        geometry=['POLYGON', 'POINT'],
        category='')
    FORT = FunctionKind(
        function="fort",
        code='164',
        geometry=['POLYGON', 'POINT'],
        category='')
    DZIALOBITNIA = FunctionKind(
        function="działobitnia",
        code='165',
        geometry=['POLYGON', 'POINT'],
        category='')
    FORTYFIKACJA_POLOWA = FunctionKind(
        function="fortyfikacja polowa",
        code='166',
        geometry=['POLYGON', 'POINT'],
        category='')
    SCHRON = FunctionKind(
        function="schron",
        code='167',
        geometry=['POLYGON', 'POINT'],
        category='')
    INNY_OBIEKT_BUDOWNICTWA_OBRONNEGO = FunctionKind(
        function="inny obiekt budownictwa obronnego",
        code='168',
        geometry=['POLYGON', 'LINE', 'POINT'],
        category='')
    ZIELEN_ZABYTKOWA = FunctionKind(
        function="zieleń zabytkowa",
        code='17',
        geometry=[''],
        category='')
    PARK_ = FunctionKind(
        function="park ",
        code='171',
        geometry=['POLYGON', 'POINT'],
        category='')
    OGROD = FunctionKind(
        function="ogród",
        code='172',
        geometry=['POLYGON', 'POINT'],
        category='')
    ARBORETUM = FunctionKind(
        function="arboretum",
        code='173',
        geometry=['POLYGON', 'POINT'],
        category='')
    ALEJA_ = FunctionKind(
        function="aleja ",
        code='174',
        geometry=['LINE'],
        category='')
    DRZEWOSTAN = FunctionKind(
        function="drzewostan",
        code='175',
        geometry=['POLYGON', 'POINT'],
        category='')
    INNA_ZIELEN_ZABYTKOWA = FunctionKind(
        function="inna zieleń zabytkowa",
        code='176',
        geometry=['POLYGON', 'LINE' 'POINT'],
        category='')
    MIEJSCE_PAMIECI = FunctionKind(
        function="miejsce pamięci",
        code='18',
        geometry=[''],
        category='')
    CMENTARZ = FunctionKind(
        function="cmentarz",
        code='181',
        geometry=[''],
        category='')
    CMENTARZ_SWIECKI = FunctionKind(
        function="cmentarz świecki",
        code='1811',
        geometry=[''],
        category='')
    CMENTARZ_WOJENNY_I_WOJSKOWY = FunctionKind(
        function="cmentarz wojenny i wojskowy",
        code='18111',
        geometry=['POLYGON', 'POINT'],
        category='')
    CMENTARZ_SPECJALNY = FunctionKind(
        function="cmentarz specjalny",
        code='18112',
        geometry=['POLYGON', 'POINT'],
        category='')
    CMENTARZ_WYZNANIOWY = FunctionKind(
        function="cmentarz wyznaniowy",
        code='1812',
        geometry=[''],
        category='')
    CMENTARZ_PRYWATNY = FunctionKind(
        function="cmentarz prywatny",
        code='1813',
        geometry=['POLYGON', 'POINT'],
        category='')
    CMENTARZ_EPIDEMICZNY = FunctionKind(
        function="cmentarz epidemiczny",
        code='1814',
        geometry=['POLYGON', 'POINT'],
        category='')
    INNY_CMENTARZ = FunctionKind(
        function="inny cmentarz",
        code='1815',
        geometry=['POLYGON', 'POINT'],
        category='')
    INNY_OBIEKT_PAMIECI = FunctionKind(
        function="inny obiekt pamięci",
        code='182',
        geometry=['POLYGON', 'LINE', 'POINT'],
        category='')
    INNY_ZABYTEK_NIERUCHOMY = FunctionKind(
        function="inny zabytek nieruchomy",
        code='19',
        geometry=['POLYGON', 'LINE', 'POINT'],
        category='')
    ZABYTEK_ARCHEOLOGICZNY = FunctionKind(
        function="zabytek archeologiczny",
        code='2',
        geometry=[''],
        category='')
    STANOWISKO_ARCHEOLOGICZNE = FunctionKind(
        function="stanowisko archeologiczne",
        code='21',
        geometry=[''],
        category='')
    STANOWISKO_OSADNICZE = FunctionKind(
        function="stanowisko osadnicze",
        code='211',
        geometry=['POLYGON', 'POINT'],
        category='')
    GRODZISKO = FunctionKind(
        function="grodzisko",
        code='2111',
        geometry=['POLYGON', 'POINT'],
        category='')
    OSADA = FunctionKind(
        function="osada",
        code='2112',
        geometry=['POLYGON', 'POINT'],
        category='')
    OBOZOWISKO = FunctionKind(
        function="obozowisko",
        code='2113',
        geometry=['POLYGON', 'POINT'],
        category='')
    JASKINIA_SCHRONISKO = FunctionKind(
        function="jaskinia/schronisko",
        code='2114',
        geometry=['POLYGON', 'POINT'],
        category='')
    RELIKTY_MIASTA_WSI = FunctionKind(
        function="relikty miasta/wsi",
        code='2115',
        geometry=['POLYGON', 'POINT'],
        category='')
    SLAD_OSADNICZY = FunctionKind(
        function="ślad osadniczy",
        code='2116',
        geometry=['POLYGON', 'POINT'],
        category='')
    INNE_NIEOKRESLONE_STANOWISKO_OSADNICZE = FunctionKind(
        function="inne/nieokreślone stanowisko osadnicze",
        code='2117',
        geometry=['POLYGON', 'POINT'],
        category='')
    ZESPOL_OSADNICZY = FunctionKind(
        function="zespół osadniczy",
        code='212',
        geometry=['POLYGON', 'POINT'],
        category='')
    STANOWISKO_SEPULKRALNE = FunctionKind(
        function="stanowisko sepulkralne",
        code='213',
        geometry=[''],
        category='')
    CMENTARZYSKO = FunctionKind(
        function="cmentarzysko",
        code='2131',
        geometry=[''],
        category='')
    CMENTARZYSKO_KURHANOWE = FunctionKind(
        function="cmentarzysko kurhanowe",
        code='21311',
        geometry=['POLYGON', 'POINT'],
        category='')
    CMENTARZYSKO_MEGALITYCZNE = FunctionKind(
        function="cmentarzysko megalityczne",
        code='21312',
        geometry=['POLYGON', 'POINT'],
        category='')
    CMENTARZYSKO_PLASKIE = FunctionKind(
        function="cmentarzysko płaskie",
        code='21313',
        geometry=['POLYGON', 'POINT'],
        category='')
    INNE_NIEOKRESLONE_CMENTARZYSKO = FunctionKind(
        function="inne/nieokreślone cmentarzysko",
        code='21314',
        geometry=['POLYGON', 'POINT'],
        category='')
    GROB = FunctionKind(
        function="grób",
        code='2132',
        geometry=[''],
        category='')
    KURHAN = FunctionKind(
        function="kurhan",
        code='21321',
        geometry=['POINT'],
        category='')
    GROB_MEGALITYCZNY = FunctionKind(
        function="grób megalityczny",
        code='21322',
        geometry=['POINT'],
        category='')
    GROB_PLASKI = FunctionKind(
        function="grób płaski",
        code='21323',
        geometry=['POINT'],
        category='')
    INNY_GROB = FunctionKind(
        function="inny grób",
        code='21324',
        geometry=['POINT'],
        category='')
    MIEJSCE_KULTU = FunctionKind(
        function="miejsce kultu",
        code='214',
        geometry=['POLYGON', 'POINT'],
        category='')
    UMOCNIENIA_OBRONNE = FunctionKind(
        function="umocnienia obronne",
        code='215',
        geometry=['POLYGON', 'POINT'],
        category='')
    STANOWISKO_O_FUNKCJI_GOSPODARCZEJ = FunctionKind(
        function="stanowisko o funkcji gospodarczej",
        code='216',
        geometry=[''],
        category='')
    MIEJSCE_EKSPLOATACJI_SUROWCA = FunctionKind(
        function="miejsce eksploatacji surowca",
        code='2161',
        geometry=['POLYGON', 'POINT'],
        category='')
    MIEJSCE_PRODUKCJI = FunctionKind(
        function="miejsce produkcji",
        code='2162',
        geometry=['POLYGON', 'POINT'],
        category='')
    SLADY_DAWNEJ_UPRAWY_ROLI_ = FunctionKind(
        function="ślady dawnej uprawy roli ",
        code='217',
        geometry=['POLYGON', 'LINE'],
        category='')
    POZOSTALOSCI_URZADZEN_KOMUNIKACYJNYCH__I_TRANSPORTOWYCH = FunctionKind(
        function="pozostałości urządzeń komunikacyjnych  i transportowych",
        code='218',
        geometry=['LINE', 'POINT'],
        category='')
    STANOWISKO_ARCHEOLOGICZNE_O_INNEJ_NIEOKRESLONEJ_FUNKCJI = FunctionKind(
        function="stanowisko archeologiczne o innej/nieokreślonej funkcji",
        code='219',
        geometry=['POLYGON', 'LINE, POINT'],
        category='')
    KOMPLEKS_OSADNICZY = FunctionKind(
        function="kompleks osadniczy",
        code='22',
        geometry=['POLYGON', 'POINT'],
        category='')
    INNY_ZABYTEK_ARCHEOLOGICZNY = FunctionKind(
        function="inny zabytek archeologiczny",
        code='23',
        geometry=['POLYGON', 'LINE', 'POINT'],
        category='')
    ZABYTEK_RUCHOMY = FunctionKind(
        function="zabytek ruchomy",
        code='3',
        geometry=['POINT'],
        category='')
    OTOCZENIE_ZABYTKU = FunctionKind(
        function="otoczenie zabytku",
        code='4',
        geometry=['POLYGON'],
        category='')
    STREFA_OCHRONY_KONSERWATORSKIEJ = FunctionKind(
        function="strefa ochrony konserwatorskiej",
        code='5',
        geometry=['POLYGON'],
        category='')
    NAZWA_MIEJSCOWA = FunctionKind(
        function="nazwa miejscowa",
        code='6',
        geometry=['POINT'],
        category='')


for function in FunctionKindEnum:
    for category in CategoryKindEnum:
        if function.value.code.startswith(category.value.code):
            function.value.category = category.value.category
