# -*- coding: utf-8 -*-
from __future__ import annotations

from enum import Enum
from dataclasses import dataclass
from .category_kind import CategoryKindEnum



@dataclass(frozen=False)
class ObjectKind:
    funkcja: str
    kod: str
    geometria: list
    kategoria: str

class ObjectKindEnum(Enum):
    
    
   
    ZABYTEK_NIERUCHOMY = ObjectKind(     
        funkcja = "zabytek nieruchomy",
        kod = "1",
        geometria = [''],
        kategoria ='')
    KRAJOBRAZ_KULTUROWY = ObjectKind(
        funkcja = "krajobraz kulturowy",
        kod = "11",
        geometria = ['POLYGON'],
        kategoria = '')
    HISTORYCZNY_UKLAD_PRZESTRZENNY = ObjectKind(
        funkcja = "historyczny układ przestrzenny",
        kod = "12",
        geometria = ['POLYGON', 'LINE'],
        kategoria = '')
    HISTORYCZNY_ZESPOL_BUDOWLANY = ObjectKind(
        funkcja = "historyczny zespół budowlany",
        kod = "13",
        geometria = [''],
        kategoria = '')
    DZIELO_ARCHITEKTURY_I_BUDOWNICTWA = ObjectKind(
        funkcja = "dzieło architektury i budownictwa",
        kod = "14",
        geometria = [''],
        kategoria = '')
    BUDYNEK_REZYDENCJONALNY = ObjectKind(
        funkcja = "budynek rezydencjonalny",
        kod = "141",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    BUDYNEK_MIESZKALNY = ObjectKind(
        funkcja = "budynek mieszkalny",
        kod = "142",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    BUDYNEK_GOSPODARCZY = ObjectKind(
        funkcja = "budynek gospodarczy",
        kod = "143",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    BUDYNEK_PRZEMYSLOWY = ObjectKind(
        funkcja = "budynek przemysłowy",
        kod = "144",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    BUDYNEK_UZYTECZNOSCI_PUBLICZNEJ = ObjectKind(
        funkcja = "budynek użyteczności publicznej",
        kod = "145",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    BUDYNEK_SAKRALNY = ObjectKind(
        funkcja = "budynek sakralny",
        kod = "146",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    MALA_ARCHITEKTURA = ObjectKind(
        funkcja = "mała architektura",
        kod = "147",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    INNE_DZIELO_ARCHITEKTURY_I_BUDOWNICTWA = ObjectKind(
        funkcja = "inne dzieło architektury i budownictwa",
        kod = "148",
        geometria = ['POLYGON','LINE', 'POINT'],
        kategoria = '')
    DZIELO_TECHNIKI_I_PRZEMYSLOWE = ObjectKind(
        funkcja = "dzieło techniki i przemysłowe",
        kod = "15",
        geometria = ['POLYGON', 'LINE', 'POINT'],
        kategoria = '')
    DZIELO_BUDOWNICTWA_OBRONNEGO = ObjectKind(
        funkcja = "dzieło budownictwa obronnego",
        kod = "16",
        geometria = [''],
        kategoria = '')
    TWIERDZA = ObjectKind(
        funkcja = "twierdza",
        kod = "161",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    ZAMEK = ObjectKind(
        funkcja = "zamek",
        kod = "162",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    DWOR_OBRONNY = ObjectKind(
        funkcja = "dwór obronny",
        kod = "163",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    FORT = ObjectKind(
        funkcja = "fort",
        kod = "164",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    DZIALOBITNIA = ObjectKind(
        funkcja = "działobitnia",
        kod = "165",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    FORTYFIKACJA_POLOWA = ObjectKind(
        funkcja = "fortyfikacja polowa",
        kod = "166",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    SCHRON = ObjectKind(
        funkcja = "schron",
        kod = "167",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    INNY_OBIEKT_BUDOWNICTWA_OBRONNEGO = ObjectKind(
        funkcja = "inny obiekt budownictwa obronnego",
        kod = "168",
        geometria = ['POLYGON', 'LINE', 'POINT'],
        kategoria = '')
    ZIELEN_ZABYTKOWA = ObjectKind(
        funkcja = "zieleń zabytkowa",
        kod = "17",
        geometria = [''],
        kategoria = '')
    PARK_ = ObjectKind(
        funkcja = "park ",
        kod = "171",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    OGROD = ObjectKind(
        funkcja = "ogród",
        kod = "172",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    ARBORETUM = ObjectKind(
        funkcja = "arboretum",
        kod = "173",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    ALEJA_ = ObjectKind(
        funkcja = "aleja ",
        kod = "174",
        geometria = ['LINE'],
        kategoria = '')
    DRZEWOSTAN = ObjectKind(
        funkcja = "drzewostan",
        kod = "175",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    INNA_ZIELEN_ZABYTKOWA = ObjectKind(
        funkcja = "inna zieleń zabytkowa",
        kod = "176",
        geometria = ['POLYGON','LINE' 'POINT'],
        kategoria = '')
    MIEJSCE_PAMIECI = ObjectKind(
        funkcja = "miejsce pamięci",
        kod = "18",
        geometria = [''],
        kategoria = '')
    CMENTARZ = ObjectKind(
        funkcja = "cmentarz",
        kod = "181",
        geometria = [''],
        kategoria = '')
    CMENTARZ_SWIECKI = ObjectKind(
        funkcja = "cmentarz świecki",
        kod = "1811",
        geometria = [''],
        kategoria = '')
    CMENTARZ_WOJENNY_I_WOJSKOWY = ObjectKind(
        funkcja = "cmentarz wojenny i wojskowy",
        kod = "18111",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    CMENTARZ_SPECJALNY = ObjectKind(
        funkcja = "cmentarz specjalny",
        kod = "18112",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    CMENTARZ_WYZNANIOWY = ObjectKind(
        funkcja = "cmentarz wyznaniowy",
        kod = "1812",
        geometria = [''],
        kategoria = '')
    CMENTARZ_PRYWATNY = ObjectKind(
        funkcja = "cmentarz prywatny",
        kod = "1813",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    CMENTARZ_EPIDEMICZNY = ObjectKind(
        funkcja = "cmentarz epidemiczny",
        kod = "1814",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    INNY_CMENTARZ = ObjectKind(
        funkcja = "inny cmentarz",
        kod = "1815",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    INNY_OBIEKT_PAMIECI = ObjectKind(
        funkcja = "inny obiekt pamięci",
        kod = "182",
        geometria = ['POLYGON', 'LINE', 'POINT'],
        kategoria = '')
    INNY_ZABYTEK_NIERUCHOMY= ObjectKind(
        funkcja = "inny zabytek nieruchomy",
        kod = "19",
        geometria = ['POLYGON', 'LINE', 'POINT'],
        kategoria = '')
    ZABYTEK_ARCHEOLOGICZNY = ObjectKind(
        funkcja = "zabytek archeologiczny",
        kod = "2",
        geometria = [''],
        kategoria = '')
    STANOWISKO_ARCHEOLOGICZNE = ObjectKind(
        funkcja = "stanowisko archeologiczne",
        kod = "21",
        geometria = [''],
        kategoria = '')
    STANOWISKO_OSADNICZE = ObjectKind(
        funkcja = "stanowisko osadnicze",
        kod = "211",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    GRODZISKO = ObjectKind(
        funkcja = "grodzisko",
        kod = "2111",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    OSADA = ObjectKind(
        funkcja = "osada",
        kod = "2112",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    OBOZOWISKO = ObjectKind(
        funkcja = "obozowisko",
        kod = "2113",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    JASKINIA_SCHRONISKO = ObjectKind(
        funkcja = "jaskinia/schronisko",
        kod = "2114",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    RELIKTY_MIASTA_WSI = ObjectKind(
        funkcja = "relikty miasta/wsi",
        kod = "2115",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    SLAD_OSADNICZY = ObjectKind(
        funkcja = "ślad osadniczy",
        kod = "2116",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    INNE_NIEOKRESLONE_STANOWISKO_OSADNICZE = ObjectKind(
        funkcja = "inne/nieokreślone stanowisko osadnicze",
        kod = "2117",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    ZESPOL_OSADNICZY = ObjectKind(
        funkcja = "zespół osadniczy",
        kod = "212",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    STANOWISKO_SEPULKRALNE = ObjectKind(
        funkcja = "stanowisko sepulkralne",
        kod = "213",
        geometria = [''],
        kategoria = '')
    CMENTARZYSKO = ObjectKind(
        funkcja = "cmentarzysko",
        kod = "2131",
        geometria = [''],
        kategoria = '')
    CMENTARZYSKO_KURHANOWE = ObjectKind(
        funkcja = "cmentarzysko kurhanowe",
        kod = "21311",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    CMENTARZYSKO_MEGALITYCZNE = ObjectKind(
        funkcja = "cmentarzysko megalityczne",
        kod = "21312",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    CMENTARZYSKO_PLASKIE = ObjectKind(
        funkcja = "cmentarzysko płaskie",
        kod = "21313",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    INNE_NIEOKRESLONE_CMENTARZYSKO = ObjectKind(
        funkcja = "inne/nieokreślone cmentarzysko",
        kod = "21314",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    GROB = ObjectKind(
        funkcja = "grób",
        kod = "2132",
        geometria = [''],
        kategoria = '')
    KURHAN = ObjectKind(
        funkcja = "kurhan",
        kod = "21321",
        geometria = ['POINT'],
        kategoria = '')
    GROB_MEGALITYCZNY = ObjectKind(
        funkcja = "grób megalityczny",
        kod = "21322",
        geometria = ['POINT'],
        kategoria = '')
    GROB_PLASKI = ObjectKind(
        funkcja = "grób płaski",
        kod = "21323",
        geometria = ['POINT'],
        kategoria = '')
    INNY_GROB = ObjectKind(
        funkcja = "inny grób",
        kod = "21324",
        geometria = ['POINT'],
        kategoria = '')
    MIEJSCE_KULTU = ObjectKind(
        funkcja = "miejsce kultu",
        kod = "214",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    UMOCNIENIA_OBRONNE = ObjectKind(
        funkcja = "umocnienia obronne",
        kod = "215",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    STANOWISKO_O_FUNKCJI_GOSPODARCZEJ = ObjectKind(
        funkcja = "stanowisko o funkcji gospodarczej",
        kod = "216",
        geometria = [''],
        kategoria = '')
    MIEJSCE_EKSPLOATACJI_SUROWCA = ObjectKind(
        funkcja = "miejsce eksploatacji surowca",
        kod = "2161",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    MIEJSCE_PRODUKCJI = ObjectKind(
        funkcja = "miejsce produkcji",
        kod = "2162",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    SLADY_DAWNEJ_UPRAWY_ROLI_ = ObjectKind(
        funkcja = "ślady dawnej uprawy roli ",
        kod = "217",
        geometria = ['POLYGON', 'LINE'],
        kategoria = '')
    POZOSTALOSCI_URZADZEN_KOMUNIKACYJNYCH__I_TRANSPORTOWYCH = ObjectKind(
        funkcja = "pozostałości urządzeń komunikacyjnych  i transportowych",
        kod = "218",
        geometria = ['LINE', 'POINT'],
        kategoria = '')
    STANOWISKO_ARCHEOLOGICZNE_O_INNEJ_NIEOKRESLONEJ_FUNKCJI = ObjectKind(
        funkcja = "stanowisko archeologiczne o innej/nieokreślonej funkcji",
        kod = "219",
        geometria = ['POLYGON', 'LINE, POINT'],
        kategoria = '')
    KOMPLEKS_OSADNICZY = ObjectKind(
        funkcja = "kompleks osadniczy",
        kod = "22",
        geometria = ['POLYGON', 'POINT'],
        kategoria = '')
    INNY_ZABYTEK_ARCHEOLOGICZNY = ObjectKind(
        funkcja = "inny zabytek archeologiczny",
        kod = "23",
        geometria = ['POLYGON', 'LINE', 'POINT'],
        kategoria = '')
    ZABYTEK_RUCHOMY = ObjectKind(
        funkcja = "zabytek ruchomy",
        kod = "3",
        geometria = ['POINT'],
        kategoria = '')
    OTOCZENIE_ZABYTKU = ObjectKind(
        funkcja = "otoczenie zabytku",
        kod = "4",
        geometria = ['POLYGON'],
        kategoria = '')
    STREFA_OCHRONY_KONSERWATORSKIEJ = ObjectKind(
        funkcja = "strefa ochrony konserwatorskiej",
        kod = "5",
        geometria = ['POLYGON'],
        kategoria = '')
    NAZWA_MIEJSCOWA = ObjectKind(
        funkcja = "nazwa miejscowa",
        kod = "6",
        geometria = ['POINT'],
        kategoria = '')

for object in ObjectKindEnum:
    for category in CategoryKindEnum:
        if object.value.kod.startswith(category.value.kod):
            object.value.kategoria=category.value.kategoria

    print(object.value.kategoria)
